# Generated by Django 5.0.4 on 2024-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0003_ticketresponse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(default="new", max_length=20),
        ),
    ]
