# Generated by Django 5.0.4 on 2024-04-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketresponse",
            name="status",
        ),
        migrations.AddField(
            model_name="ticketresponse",
            name="updated_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
