# Generated by Django 5.0.4 on 2024-04-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0005_remove_ticketresponse_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketresponse",
            name="updated_status",
        ),
        migrations.AlterField(
            model_name="ticketresponse",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="ticket_app.ticket",
            ),
        ),
    ]
